/* =====================================================================
   Ryze — wizard.js : assistant « Nouveau dossier » (5 étapes)
   et carnet de suivi biothérapique imprimable
   ===================================================================== */
'use strict';
(function (R) {
  const S = R.S, esc = R.esc;
  const opt = (arr, val, lab, sel) => arr.map(x => `<option value="${esc(val(x))}"${val(x) === sel ? ' selected' : ''}>${esc(lab(x))}</option>`).join('');
  const medecins = () => S.users.filter(u => u.medecin && u.actif);

  function nouveauW() {
    const u = R.user();
    return { step: 1, d: { nom: '', prenom: '', ddn: '', sexe: 'F', ipp: '', tel: '', poids: '', taille: '', pathologie: 'MC', montreal: '', dateDiag: '', medecinId: u && u.medecin ? u.id : (medecins()[0] || {}).id, traitementsAssocies: '', allergies: '', antecedentsBio: '', comorbidites: '' },
      bilan: R.BILAN_PRE.map(b => ({ id: b.id, statut: 'attente', date: '', commentaire: '' })), protocoleId: null, dateDebut: R.addDays(R.today(), 7), heure: '09:00', fauteuil: 1, horizon: 365, carnetMixte: true, induction: [], entretien: null, premed: '', surv: {}, survCustom: [] };
  }
  const W = () => R.ui.w || (R.ui.w = nouveauW());
  const protoTemp = () => Object.assign({}, R.proto(W().protocoleId), { induction: W().induction, entretien: W().entretien });
  const calcCures = () => { const w = W(); if (!w.protocoleId) return []; const cures = R.genererCures(protoTemp(), w.dateDebut, +w.d.poids || 70, w.horizon); return R.reserverCures(cures, w.heure); };
  function survDefaults(pr) { const s = {}; R.SURVEILLANCE.forEach(it => { s[it.id] = { on: pr.surveillanceDefaut.includes(it.id) && !(it.id === 'fcu' && W().d.sexe === 'M'), jours: it.mode === 'echeances' ? [...it.jours] : null, tousLes: it.tousLes || null }; }); return s; }
  const field = (label, k, type, extra, root) => { const w = W(); const v = root ? w[k] : w.d[k]; return `<div class="field${extra && extra.span ? ' span' + extra.span : ''}"><label>${label}</label><input type="${type || 'text'}" id="w-${k}" value="${esc(v ?? '')}" data-input="wBind" data-k="${k}" ${root ? 'data-root="1"' : ''} ${extra && extra.attrs ? extra.attrs : ''}>${extra && extra.hint ? `<span class="hint">${extra.hint}</span>` : ''}</div>`; };

  /* ---------- Étapes ---------- */
  function section(w, i, titre, resume, body, dernier) {
    const open = (w.sec ?? 0) === i;
    return `<div class="acc${open ? ' open' : ''}"><button type="button" class="acc-head" data-action="wSection" data-i="${i}"><span class="step-n" style="border-color:${open ? 'var(--accent)' : 'var(--line-strong)'};color:${open ? 'var(--accent-ink)' : 'var(--muted)'}">${i + 1}</span><h2>${titre}</h2><span class="sum">${open ? 'ouvert' : esc(resume)}</span>${R.icon(open ? 'chevD' : 'chevR', 'ico')}</button>${open ? `<div class="acc-body"><div class="mt16">${body}</div>${dernier ? '' : `<div class="row mt16" style="justify-content:flex-end"><button type="button" class="btn primary" data-action="wSection" data-i="${i + 1}">Section suivante ${R.icon('chevR')}</button></div>`}</div>` : ''}</div>`;
  }
  function step1(w) {
    const d = w.d; const montrealAide = d.pathologie === 'MC' ? 'A1 < 17 ans · A2 17–40 · A3 > 40 | L1 iléale · L2 colique · L3 iléo-colique · L4 haute | B1 inflammatoire · B2 sténosante · B3 pénétrante · p périnéale' : 'E1 rectite · E2 colite gauche · E3 pancolite | S0 rémission · S1 légère · S2 modérée · S3 sévère';
    const app = w.bilan.filter(b => b.statut !== 'na'), fait = app.filter(b => b.statut.startsWith('fait')).length;
    const idBody = `<div class="form-grid">${field('Nom', 'nom', 'text', { attrs: 'required style="text-transform:uppercase"' })}${field('Prénom', 'prenom', 'text', { attrs: 'required' })}${field('N° de dossier (IPP)', 'ipp', 'text', { attrs: 'placeholder="laisser vide : numéro automatique"', hint: 'identifiant du patient dans le système de l’hôpital ; sinon numéro généré par Ryze' })}
      ${field('Date de naissance', 'ddn', 'date', { attrs: 'required' })}<div class="field"><label>Sexe</label><select data-change="wBindR" data-k="sexe"><option value="F"${d.sexe === 'F' ? ' selected' : ''}>Femme</option><option value="M"${d.sexe === 'M' ? ' selected' : ''}>Homme</option></select></div>${field('Téléphone', 'tel', 'tel')}
      ${field('Poids (kg)', 'poids', 'number', { attrs: 'step="0.1" required' })}${field('Taille (cm)', 'taille', 'number')}<div class="field"><label>Médecin référent</label><select data-change="wBind" data-k="medecinId">${opt(medecins(), u => u.id, u => R.userName(u.id), d.medecinId)}</select></div></div>`;
    const malBody = `<div class="form-grid"><div class="field"><label>Pathologie</label><select data-change="wBindR" data-k="pathologie">${opt(Object.keys(R.PATHOS), k => k, k => R.PATHOS[k].label, d.pathologie)}</select></div>${field('Classification de Montréal', 'montreal', 'text', { attrs: `placeholder="${d.pathologie === 'MC' ? 'ex. A2 L3 B1p' : 'ex. E3 S2'}"` })}${field('Date du diagnostic', 'dateDiag', 'date')}<div class="field span3"><span class="hint">${montrealAide}</span></div></div>`;
    const atcdBody = `<div class="form-grid">${field('Traitements associés', 'traitementsAssocies', 'text', { attrs: 'placeholder="ex. azathioprine 150 mg/j, mésalazine 4 g/j"' })}${field('Allergies', 'allergies', 'text', { attrs: 'placeholder="ex. pénicilline (urticaire)"' })}${field('Biothérapies antérieures', 'antecedentsBio', 'text', { attrs: 'placeholder="ex. infliximab 2019–2024, perte de réponse (ADA+)"' })}${field('Comorbidités / facteurs de risque', 'comorbidites', 'text', { span: 3, attrs: 'placeholder="ex. tabagisme actif, antécédent de zona, insuffisance cardiaque"' })}</div>`;
    return section(w, 0, 'Identité', d.nom ? `${d.nom.toUpperCase()} ${d.prenom} · ${d.ipp || 'n° automatique'} · ${d.poids || '?'} kg` : 'à compléter', idBody)
      + section(w, 1, 'Maladie', `${R.PATHOS[d.pathologie]?.label}${d.montreal ? ' · ' + d.montreal : ''}`, malBody)
      + section(w, 2, 'Antécédents et traitements', [d.traitementsAssocies, d.allergies, d.antecedentsBio].filter(Boolean).join(' · ') || 'rien renseigné', atcdBody)
      + section(w, 3, 'Bilan pré-thérapeutique (optionnel)', `${fait}/${app.length} faits`, step2(w), true);
  }
  function step2(w) {
    const app = w.bilan.filter(b => b.statut !== 'na'), fait = app.filter(b => b.statut.startsWith('fait')).length; const cats = [...new Set(R.BILAN_PRE.map(b => b.cat))];
    return `<div class="row between mb8"><span class="small muted">Check-list GETAID 2021 / ECCO 2025 — modifiable ensuite dans le dossier</span><div class="row"><div class="meter" style="width:140px"><i class="${fait === app.length ? 'good' : 'warn'}" style="width:${app.length ? (fait / app.length * 100).toFixed(0) : 0}%"></i></div><span class="num small">${fait}/${app.length}</span><button type="button" class="btn sm" data-action="wBilanTout">Tout marquer « fait — normal »</button></div></div>
      <div class="tbl-wrap"><table class="tbl"><thead><tr><th>Catégorie</th><th>Examen</th><th>Statut</th><th>Date</th><th>Résultat / commentaire</th></tr></thead><tbody>${cats.map(cat => R.BILAN_PRE.filter(b => b.cat === cat).map(b => { const r = w.bilan.find(x => x.id === b.id); return `<tr class="${r.statut === 'na' ? 'done' : ''}"><td class="small muted">${esc(cat)}</td><td>${esc(b.label)}</td><td><select class="inline-input w150" data-change="wBilan" data-bid="${b.id}" data-k="statut">${opt(Object.keys(R.BILAN_STATUTS), k => k, k => R.BILAN_STATUTS[k], r.statut)}</select></td><td><input type="date" class="inline-input w150" value="${esc(r.date)}" data-change="wBilan" data-bid="${b.id}" data-k="date"></td><td><input type="text" class="inline-input" style="width:100%!important" value="${esc(r.commentaire)}" data-input="wBilan" data-bid="${b.id}" data-k="commentaire" placeholder="résultat"></td></tr>`; }).join('')).join('')}</tbody></table></div>
      <p class="small muted mt8">Le dépistage de la tuberculose (IGRA + radiographie) et de l’hépatite B conditionne la première séance : une infection tuberculeuse latente se traite ≥ 3 semaines avant le début. Les vaccins vivants sont contre-indiqués sous traitement : à administrer ≥ 3–4 semaines avant.</p>`;
  }
  function step3(w) {
    const pr = w.protocoleId ? R.proto(w.protocoleId) : null; const cures = calcCures(); const art = pr ? R.article(pr.articleId) : null;
    const carte = p => `<button type="button" class="proto" style="text-align:left;cursor:pointer;${w.protocoleId === p.id ? 'border-color:var(--accent);background:var(--accent-tint)' : ''}" data-action="wProto" data-id="${p.id}"><div class="row between"><h3>${esc(p.dci)}</h3>${w.protocoleId === p.id ? R.icon('check', 'ico') : ''}</div><div class="spec">${esc(p.classe)} · ${esc(p.voie)} · ${p.indications.join(' / ')}</div><div class="small">${p.induction.map(e => e.label).join(' · ')} puis ${esc(p.entretien?.label || '')}</div></button>`;
    const indiques = S.protocoles.filter(p => p.indications.includes(w.d.pathologie)), autres = S.protocoles.filter(p => !p.indications.includes(w.d.pathologie));
    return `<section class="card mb16"><div class="card-head"><div><h2>Choix du protocole</h2><div class="sub">protocoles indiqués pour ${esc(R.PATHOS[w.d.pathologie]?.label)} — les autres restent accessibles</div></div></div><div class="card-body"><div class="proto-grid">${indiques.map(carte).join('')}</div>${autres.length ? `<details class="mt16"><summary class="small muted" style="cursor:pointer">Autres protocoles (${autres.length})</summary><div class="proto-grid mt8">${autres.map(carte).join('')}</div></details>` : ''}</div></section>
    ${pr ? `<div class="grid c21"><section class="card"><div class="card-head"><div><h2>Cycles de traitement — ${esc(pr.dci)}</h2><div class="sub">doses recalculées sur ${w.d.poids || '?'} kg · arrondi au flacon de ${art ? art.unite + ' ' + art.uniteLib : '—'}</div></div></div><div class="card-body">
        <div class="form-grid mb16"><div class="field span2"><label>Posologie</label><select data-change="wVariante">${R.varianteOptions(pr, w.variante)}</select><span class="hint">applique les doses et l’intervalle de la variante ; tout reste modifiable ci-dessous</span></div><div class="field"><label>Date de la 1re cure (J0)</label><input type="date" value="${w.dateDebut}" data-change="wBindR" data-k="dateDebut" data-root="1"></div><div class="field"><label>Poids (kg)</label><input type="number" step="0.1" value="${esc(w.d.poids)}" data-change="wBindR" data-k="poids"></div><div class="field"><label>Heure souhaitée</label><input type="time" value="${w.heure}" data-change="wBindR" data-k="heure" data-root="1"><span class="hint">le fauteuil est attribué automatiquement</span></div><div class="field"><label>Horizon de planification</label><select data-change="wBindR" data-k="horizon" data-root="1">${[[182, '6 mois'], [365, '12 mois'], [548, '18 mois']].map(x => `<option value="${x[0]}"${w.horizon == x[0] ? ' selected' : ''}>${x[1]}</option>`).join('')}</select></div></div>
        <div class="caps mb8">Phase d’induction</div><div class="tbl-wrap"><table class="tbl"><thead><tr><th>Étape</th><th>Jour</th><th>Dose ${pr.doseType === 'mgkg' ? '(mg/kg)' : pr.doseType === 'palier' ? '(palier)' : pr.doseType === 'po' ? '' : '(mg)'}</th><th>Voie</th><th>Calcul</th><th></th></tr></thead><tbody>${w.induction.map((e, i) => { const d = R.doseEtape(protoTemp(), e, +w.d.poids || 70, 'induction'); return `<tr><td><input class="inline-input w70" value="${esc(e.label)}" data-change="wStep" data-i="${i}" data-k="label"></td><td><input type="number" class="inline-input w70" value="${e.jour}" data-change="wStep" data-i="${i}" data-k="jour"></td><td>${pr.doseType === 'palier' || pr.doseType === 'po' ? `<span class="small">${esc(d.texte)}</span>` : `<input type="number" step="0.5" class="inline-input w70" value="${e.dose ?? ''}" data-change="wStep" data-i="${i}" data-k="dose">`}</td><td><select class="inline-input" data-change="wStep" data-i="${i}" data-k="voie">${['IV', 'SC', 'PO'].map(v => `<option${e.voie === v ? ' selected' : ''}>${v}</option>`).join('')}</select></td><td class="small">${esc(d.texte)}${d.flacons ? ` · <b>${d.flacons} fl.</b>` : ''}</td><td class="actions"><button type="button" class="btn sm ghost" data-action="wDelStep" data-i="${i}">${R.icon('x')}</button></td></tr>`; }).join('')}</tbody></table></div><button type="button" class="btn sm mt8" data-action="wAddStep">Ajouter une étape d’induction</button>
        <div class="caps mt16 mb8">Phase d’entretien</div><div class="form-grid"><div class="field"><label>Début (jour après J0)</label><input type="number" value="${w.entretien.debutJour}" data-change="wEnt" data-k="debutJour"></div><div class="field"><label>Intervalle (jours)</label><input type="number" value="${w.entretien.intervalleJours}" data-change="wEnt" data-k="intervalleJours"><span class="hint">28 = 4 sem · 42 = 6 sem · 56 = 8 sem · 84 = 12 sem</span></div><div class="field"><label>Dose ${(w.entretien.doseType || pr.doseType) === 'mgkg' ? '(mg/kg)' : '(mg)'}</label><input type="number" step="0.5" value="${w.entretien.dose ?? ''}" data-change="wEnt" data-k="dose" ${pr.doseType === 'po' ? 'disabled' : ''}></div><div class="field"><label>Voie</label><select data-change="wEnt" data-k="voie">${['IV', 'SC', 'PO'].map(v => `<option${w.entretien.voie === v ? ' selected' : ''}>${v}</option>`).join('')}</select></div></div>
        <div class="caps mt16 mb8">Carnet de suivi</div><label class="check${w.carnetMixte ? ' on' : ''}"><input type="checkbox" data-change="wMixte"${w.carnetMixte ? ' checked' : ''}><span><b>Planification unifiée</b><span>séances et contrôles dans un seul calendrier, dans le dossier comme dans le carnet imprimé. Décoché : deux tableaux séparés.</span></span></label>
        <div class="caps mt16 mb8">Prémédication</div><div class="field"><select data-change="wBindR" data-k="premed" data-root="1"><option${w.premed === 'Aucune' ? ' selected' : ''}>Aucune</option><option${w.premed === 'Paracétamol 1 g PO' ? ' selected' : ''}>Paracétamol 1 g PO</option><option${w.premed === 'Paracétamol 1 g + dexchlorphéniramine 5 mg IV' ? ' selected' : ''}>Paracétamol 1 g + dexchlorphéniramine 5 mg IV</option><option${w.premed === 'Paracétamol 1 g + dexchlorphéniramine 5 mg + hydrocortisone 100 mg IV' ? ' selected' : ''}>Paracétamol 1 g + dexchlorphéniramine 5 mg + hydrocortisone 100 mg IV</option></select><span class="hint">Protocole : ${esc(pr.premedication)}</span></div>
      </div></section>
      <section class="card"><div class="card-head"><div><h2>Calendrier prévisionnel</h2><div class="sub">${cures.length} cures · dernière le ${R.fmtDate(cures[cures.length - 1]?.datePrevue)}</div></div></div><div class="card-body flush tbl-wrap"><table class="tbl"><thead><tr><th>N°</th><th>Phase</th><th>Date · créneau</th><th>Dose</th><th class="right">Fl.</th></tr></thead><tbody>${cures.map(c => `<tr><td class="mono">${c.n}</td><td>${c.phase === 'Induction' ? R.badge('info', c.label) : `<span class="tag">${c.label}</span>`} <span class="xs muted">${c.voie}</span></td><td class="nowrap">${R.fmtDate(c.datePrevue, { weekday: 'short', day: '2-digit', month: '2-digit', year: '2-digit' })}${c.voie === 'IV' ? `<div class="xs muted">${c.heure} · F${c.fauteuil || '?'}${c.decalee ? ' · <b>décalée</b>' : ''}${c.sansCreneau ? ' · <b style="color:var(--crit-ink)">sans créneau</b>' : ''}</div>` : ''}</td><td class="small dose">${esc(c.doseTexte)}</td><td class="right num">${c.flacons || '—'}</td></tr>`).join('')}</tbody></table></div><div class="card-foot">Chaque séance IV réserve un fauteuil libre (${R.hdj().fauteuils} fauteuils, ${R.hdj().maxParJour} séances/jour max). Une séance « décalée » a glissé au premier jour disponible.</div></section></div>` : '<div class="callout info">Sélectionnez un protocole pour construire les cycles.</div>'}`;
  }
  function step4(w) {
    const cats = [...new Set(R.SURVEILLANCE.map(s => s.cat))];
    return `<div class="grid c21"><section class="card"><div class="card-head"><div><h2>Plan de surveillance</h2><div class="sub">proposition issue du protocole — ajustez les éléments et les échéances</div></div></div><div class="card-body stack">${cats.map(cat => `<div><div class="caps mb8">${esc(cat)}</div><div class="stack" style="gap:8px">${R.SURVEILLANCE.filter(s => s.cat === cat).map(s => { const c = w.surv[s.id] || { on: false }; return `<div class="check${c.on ? ' on' : ''}" style="flex-wrap:wrap"><input type="checkbox" id="sv-${s.id}" data-change="wSurvToggle" data-id="${s.id}"${c.on ? ' checked' : ''}><label for="sv-${s.id}" class="grow" style="cursor:pointer"><b>${esc(s.label)}</b><span>${s.mode === 'cure' ? 'à chaque cure' : s.mode === 'periodique' ? 'périodique' : 'échéances datées'}${s.cible ? ' · cible ' + esc(s.cible) : ''}</span></label>
          ${c.on && s.mode === 'echeances' ? `<div class="row" style="width:100%;padding-left:24px">${c.jours.map((j, k) => `<span class="row" style="gap:4px"><span class="tag">${R.libelleJour(j)}</span><input type="date" class="inline-input w150" value="${R.addDays(w.dateDebut, j)}" data-change="wSurvDate" data-id="${s.id}" data-j="${k}"></span>`).join('')}<button type="button" class="btn sm ghost" data-action="wSurvAddDate" data-id="${s.id}">+ échéance</button></div>` : ''}
          ${c.on && s.mode === 'periodique' ? `<div class="row" style="width:100%;padding-left:24px"><span class="small">tous les</span><input type="number" class="inline-input w70" value="${c.tousLes}" data-change="wSurvPeriod" data-id="${s.id}"><span class="small">jours (${Math.floor(w.horizon / c.tousLes)} échéances sur l’horizon)</span></div>` : ''}</div>`; }).join('')}</div></div>`).join('')}</div></section>
    <section class="card"><div class="card-head"><h2>Éléments personnalisés</h2></div><div class="card-body stack">${w.survCustom.map((c, i) => `<div class="row between subtle"><div><b>${esc(c.label)}</b><div class="small muted">${R.fmtDateLong(c.date)}</div></div><button type="button" class="btn sm ghost" data-action="wSurvCustomDel" data-i="${i}">${R.icon('x')}</button></div>`).join('') || '<span class="small muted">Aucun élément ajouté</span>'}
      <div class="form-grid"><div class="field span2"><label>Libellé</label><input type="text" id="w-custom-label" placeholder="ex. IRM pelvienne (fistule), consultation stomathérapie, ostéodensitométrie"></div><div class="field"><label>Échéance</label><input type="date" id="w-custom-date" value="${R.addDays(w.dateDebut, 90)}"></div></div><button type="button" class="btn sm" data-action="wSurvCustomAdd">Ajouter</button>
      <div class="callout info">Objectifs STRIDE-II : réponse clinique à court terme, rémission clinique + CRP normale, calprotectine 100–250 µg/g à moyen terme, cicatrisation endoscopique à 6–12 mois. Réévaluer tous les 3 mois si maladie active.</div></div></section></div>`;
  }
  function step5(w) {
    const pr = R.proto(w.protocoleId), cures = calcCures(), d = w.d; const app = w.bilan.filter(b => b.statut !== 'na'), attente = app.filter(b => b.statut === 'attente');
    const apercu = construirePatient();
    return `<div class="callout mb16"><b>${esc(d.nom.toUpperCase())} ${esc(d.prenom)}</b> · ${esc(pr.dci)} · ${cures.length} séances planifiées du ${R.fmtDate(cures[0]?.datePrevue)} au ${R.fmtDate(cures[cures.length - 1]?.datePrevue)} · ${R.SURVEILLANCE.filter(s => w.surv[s.id]?.on).length + w.survCustom.length} éléments de surveillance${attente.length ? ` · <span style="color:var(--warn-ink)">${attente.length} examen(s) du bilan en attente</span>` : ''}. Vérifiez le carnet ci-dessous puis enregistrez.</div>
    ${R.carnetHTML(apercu)}`;
  }

  R.pages.nouveau = {
    render() {
      const w = W(); const steps = ['Patient', 'Traitement et cycles', 'Carnet'];
      return `<div class="page-head"><div><h1>Nouveau dossier de biothérapie</h1><p>Trois étapes : le patient, le protocole avec ses cycles, puis le carnet à imprimer</p></div><div class="page-actions"><button class="btn ghost" data-action="wAbandon">Abandonner</button></div></div>
      <div class="stepper" style="grid-template-columns:repeat(3,1fr)">${steps.map((s, i) => `<div class="step${w.step === i + 1 ? ' active' : w.step > i + 1 ? ' done' : ''}"><span class="step-n">${w.step > i + 1 ? '✓' : i + 1}</span><span class="lbl">${s}</span></div>`).join('')}</div>
      ${w.step === 1 ? step1(w) : ''}
      ${w.step === 2 ? step3(w) + (w.protocoleId ? '<div class="mt16">' + step4(w) + '</div>' : '') : ''}
      ${w.step === 3 ? step5(w) : ''}
      <div class="row between mt24"><div>${w.step > 1 ? `<button class="btn" data-action="wPrev">${R.icon('chevL')}Précédent</button>` : ''}</div><div class="row">${w.step < 3 ? `<button class="btn primary" data-action="wNext">Suivant ${R.icon('chevR')}</button>` : `<button class="btn" data-action="wCreate">Enregistrer le dossier</button><button class="btn primary" data-action="wCreatePrint">${R.icon('print')}Enregistrer et imprimer le carnet</button>`}</div></div>`;
    }
  };

  function valider(step) {
    const w = W();
    if (step === 1) { const m = ['nom', 'prenom', 'ddn', 'poids'].filter(k => !String(w.d[k] || '').trim()); if (m.length) { R.toast('Champs obligatoires : ' + m.join(', '), 'crit'); return false; } }
    if (step === 2 && !w.protocoleId) { R.toast('Choisissez un protocole', 'crit'); return false; }
    return true;
  }
  function construirePatient() {
    const w = W(); const pr = R.proto(w.protocoleId), cures = calcCures(), surveillance = [];
    Object.keys(w.surv).filter(id => w.surv[id].on).forEach(id => { const it = R.surv(id), cfg = w.surv[id]; if (it.mode === 'cure') surveillance.push({ id, label: it.label, cat: it.cat, mode: 'cure', echeance: null, statut: 'cure' }); else if (it.mode === 'periodique') { for (let j = cfg.tousLes; j <= w.horizon; j += cfg.tousLes) surveillance.push({ id, label: it.label, cat: it.cat, mode: 'echeance', jour: j, echeance: R.addDays(w.dateDebut, j), statut: 'prevue' }); } else cfg.jours.forEach(j => surveillance.push({ id, label: it.label, cat: it.cat, mode: 'echeance', jour: j, echeance: R.addDays(w.dateDebut, j), statut: 'prevue', cible: it.cible })); });
    w.survCustom.forEach(c => surveillance.push({ id: R.uid('sv'), label: c.label, cat: 'Personnalisé', mode: 'echeance', jour: R.diffDays(w.dateDebut, c.date), echeance: c.date, statut: 'prevue' }));
    surveillance.sort((a, b) => (a.jour || 0) - (b.jour || 0));
    const d = w.d;
    return { id: R.uid('p'), ipp: d.ipp.trim() || R.numeroDossier(), nom: d.nom.trim().toUpperCase(), prenom: d.prenom.trim(), ddn: d.ddn, sexe: d.sexe, poids: +d.poids, taille: +d.taille || null, tel: d.tel, pathologie: d.pathologie, montreal: d.montreal, dateDiag: d.dateDiag, medecinId: d.medecinId, protocoleId: pr.id, dateDebut: w.dateDebut, traitementsAssocies: d.traitementsAssocies || '—', allergies: d.allergies || '—', antecedentsBio: d.antecedentsBio || 'Aucune biothérapie antérieure', comorbidites: d.comorbidites, premedication: w.premed, statut: 'induction', motifSuspension: '', cures, surveillance, carnetMixte: !!w.carnetMixte, cycleCourant: 1, historiqueProtocoles: [{ cycle: 1, protocoleId: pr.id, dateDebut: w.dateDebut, poids: +d.poids, statut: 'en cours', posologie: w.variante != null && pr.variantes ? pr.variantes[w.variante].nom : 'Posologie standard', modifications: [], planifieJusqua: cures.length ? cures[cures.length - 1].label : '—', par: S.user }], bilan: JSON.parse(JSON.stringify(w.bilan)), notes: [{ date: R.today(), heure: new Date().toTimeString().slice(0, 5), par: S.user, txt: `Dossier créé — ${pr.dci}, ${w.induction.length} étape(s) d’induction puis entretien tous les ${w.entretien.intervalleJours} j.` }], creeLe: R.today(), creePar: S.user, derniereCure: null, protocoleSnapshot: { induction: w.induction, entretien: w.entretien } };
  }
  function creer() { if (!valider(1) || !valider(2)) return null; const p = construirePatient(); S.patients.push(p); R.journal(`Dossier créé — ${R.nomComplet(p)} (${R.proto(p.protocoleId).dci})`); R.ui.w = null; R.touch(); return p; }
  Object.assign(R.actions, {
    wBind(el) { const w = W(); if (el.dataset.root) w[el.dataset.k] = el.value; else w.d[el.dataset.k] = el.value; },
    wBindR(el) { R.actions.wBind(el); const w = W(); if (el.dataset.k === 'sexe' && w.protocoleId) w.surv = Object.assign(survDefaults(R.proto(w.protocoleId)), Object.fromEntries(Object.entries(w.surv).filter(([k]) => k !== 'fcu'))); R.render(); },
    wNext() { const w = W(); if (!valider(w.step)) return; w.step++; R.render(); },
    wPrev() { W().step--; R.render(); },
    wAbandon() { R.confirmer('Abandonner la saisie ?', 'Les informations saisies dans l’assistant seront perdues.', 'wAbandonOk'); },
    wAbandonOk() { R.ui.w = null; R.go('patients'); },
    wBilan(el) { const b = W().bilan.find(x => x.id === el.dataset.bid); b[el.dataset.k] = el.value; if (el.dataset.k === 'statut') { if (el.value.startsWith('fait') && !b.date) b.date = R.today(); R.render(); } },
    wBilanTout() { W().bilan.forEach(b => { if (b.statut === 'attente') { b.statut = 'fait_normal'; b.date = b.date || R.today(); } }); R.render(); },
    wProto(el) { const w = W(); const pr = R.proto(el.dataset.id); w.protocoleId = pr.id; w.variante = null; w.induction = JSON.parse(JSON.stringify(pr.induction)); w.entretien = JSON.parse(JSON.stringify(pr.entretien || { debutJour: 56, intervalleJours: 56, dose: null, voie: 'IV', label: '' })); w.surv = survDefaults(pr); w.premed = /Non systématique|Aucune|—/.test(pr.premedication) ? 'Aucune' : pr.premedication; R.render(); },
    wStep(el) { const e = W().induction[+el.dataset.i]; const k = el.dataset.k; e[k] = (k === 'label' || k === 'voie') ? el.value : (el.value === '' ? null : +el.value); R.render(); },
    wAddStep() { const w = W(); const last = w.induction[w.induction.length - 1] || { jour: -14, dose: null, voie: 'IV' }; const jour = last.jour + 14; w.induction.push({ label: R.libelleJour(jour), jour, dose: last.dose, voie: last.voie }); R.render(); },
    wDelStep(el) { W().induction.splice(+el.dataset.i, 1); R.render(); },
    wEnt(el) { const k = el.dataset.k; W().entretien[k] = k === 'voie' ? el.value : (el.value === '' ? null : +el.value); R.render(); },
    wSurvToggle(el) { const w = W(); const s = R.surv(el.dataset.id); w.surv[s.id] = w.surv[s.id] || { on: false, jours: s.jours ? [...s.jours] : null, tousLes: s.tousLes || null }; w.surv[s.id].on = el.checked; R.render(); },
    wSurvDate(el) { const w = W(); w.surv[el.dataset.id].jours[+el.dataset.j] = R.diffDays(w.dateDebut, el.value); },
    wSurvAddDate(el) { const w = W(); const j = w.surv[el.dataset.id].jours; j.push((j[j.length - 1] || 0) + 182); R.render(); },
    wSurvPeriod(el) { W().surv[el.dataset.id].tousLes = Math.max(7, +el.value || 91); R.render(); },
    wSurvCustomAdd() { const l = document.getElementById('w-custom-label').value.trim(), d = document.getElementById('w-custom-date').value; if (!l || !d) { R.toast('Libellé et date requis', 'crit'); return; } W().survCustom.push({ label: l, date: d }); R.render(); },
    wSurvCustomDel(el) { W().survCustom.splice(+el.dataset.i, 1); R.render(); },
    wMixte(el) { W().carnetMixte = el.checked; R.render(); },
    wSection(el) { W().sec = +el.dataset.i; R.render(); },
    wVariante(el) { const w = W(); const pr = R.proto(w.protocoleId); const v = el.value === '' ? null : pr.variantes[+el.value]; w.variante = el.value === '' ? null : +el.value; const tmp = R.appliquerVariante(pr, v); w.induction = tmp.induction; w.entretien = tmp.entretien; R.render(); },
    wCreate() { const p = creer(); if (!p) return; R.toast('Dossier créé, carnet généré', 'good'); R.go('patient', { id: p.id }); },
    wCreatePrint() { const p = creer(); if (!p) return; R.go('carnet', { id: p.id }); setTimeout(() => window.print(), 400); },
    imprimer() { window.print(); }
  });

  /* ---------- Carnet de suivi (document imprimable) ---------- */
  R.pages.carnet = {
    render(params) {
      const p = R.patient(params.id); if (!p) return '<div class="empty">Dossier introuvable.</div>';
      return `<div class="row between no-print mb16"><button class="btn" data-go="patient" data-params='${R.params({ id: p.id })}'>${R.icon('back')}Retour au dossier</button><div class="row"><span class="small muted">Format A4 · 4 pages</span><button class="btn primary" data-action="imprimer">${R.icon('print')}Imprimer / PDF</button></div></div>${R.carnetHTML(p)}`;
    }
  };
  R.carnetHTML = function (p) {
      const pr = R.proto(p.protocoleId), s = S.settings, art = R.article(pr.articleId), t = R.today();
      const band = `<div class="doc-band"><div><b>${esc(s.etablissement)}</b>${esc(s.service)}<br>${esc(s.unite)}</div><div class="r"><b>Carnet de suivi biothérapique</b>${esc(R.nomComplet(p))} · IPP ${esc(p.ipp)}<br>Édité le ${R.fmtDate(t)}</div></div>`;
      const foot = n => `<div class="doc-foot"><span>Document remis au patient — à présenter à chaque venue et à tout professionnel de santé consulté</span><span>Page ${n} / 4</span></div>`;
      const cureCourante = R.prochaineCure(p) || R.derniereCure(p);
      const vacc = p.bilan.find(b => b.id === 'vacc'); const bilanApp = p.bilan.filter(b => b.statut !== 'na');
      const ech = p.surveillance.filter(x => x.mode === 'echeance' && x.statut !== 'annulee').sort((a, b) => a.echeance.localeCompare(b.echeance));
      const curesVis = p.cures.filter(c => c.statut !== 'annulee');
      const hist = p.historiqueProtocoles || [];
      const histHTML = hist.length > 1 || (hist[0] && (hist[0].modifications || []).length) ? `<div class="doc-h2">Historique du traitement</div><table class="doc-table"><thead><tr><th>Cycle</th><th>Protocole</th><th>Début (J0)</th><th>Planifié jusqu’à</th><th>Fin / arrêt</th><th>Motif et modifications</th></tr></thead><tbody>${hist.map(x => `<tr><td class="m">${x.cycle}</td><td><b>${esc(R.proto(x.protocoleId)?.dci || x.protocoleId)}</b></td><td class="m">${R.fmtDate(x.dateDebut)}</td><td class="m">${esc(x.planifieJusqua || '—')}</td><td>${x.dateFin ? `${R.fmtDate(x.dateFin)} — arrêté à ${esc(x.arreteA || '')}` : 'en cours'}</td><td style="font-size:8.5pt">${x.motif ? 'Mise en place : ' + esc(x.motif) + '<br>' : ''}${x.motifFin ? 'Arrêt : ' + esc(x.motifFin) + '<br>' : ''}${(x.modifications || []).map(m => R.fmtDate(m.date) + ' — ' + esc(m.txt)).join('<br>')}</td></tr>`).join('')}</tbody></table>` : '';
      const ligneCure = c => `<tr class="${c.statut === 'realisee' ? 'doc-done' : ''}"><td class="m">${R.fmtDate(c.datePrevue)}${c.heure && c.voie === 'IV' ? '<br><span style="color:#7E8C88">' + c.heure + '</span>' : ''}</td><td><b>Séance</b> ${esc(c.label)}${(c.cycle || 1) > 1 ? ' <span style="color:#7E8C88">(c' + c.cycle + ')</span>' : ''}<br><span style="font-size:8pt;color:#7E8C88">${esc(R.proto(c.protocoleId || p.protocoleId)?.dci || '')} · ${esc(c.phase)} · ${c.voie}</span></td><td>${c.statut === 'realisee' ? (c.dose ? c.dose + ' mg' : esc(c.doseTexte)) : esc(c.doseTexte)}${c.flacons ? ` <span style="color:#7E8C88">(${c.flacons} u.)</span>` : ''}</td><td class="m">${c.dateReelle ? R.fmtDate(c.dateReelle) : ''}</td><td style="font-size:8.5pt">${c.statut === 'realisee' ? (c.poids ? c.poids + ' kg · ' : '') + (c.lot ? 'lot ' + esc(c.lot) + ' · ' : '') + esc((c.tolerance || '').slice(0, 60)) : c.statut === 'reportee' ? 'Reportée — ' + esc((c.motif || '').slice(0, 50)) : ''}</td><td style="font-size:8pt">${c.statut === 'realisee' ? esc(R.userName(c.ide)) : ''}</td></tr>`;
      const ligneCtrl = x => `<tr class="${x.statut === 'faite' ? 'doc-done' : ''}"><td class="m">${R.fmtDate(x.echeance)}</td><td><b>Contrôle</b> ${esc(x.label)}<br><span style="font-size:8pt;color:#7E8C88">${esc(x.cat)} · ${R.libelleJour(x.jour || 0)}${x.cible ? ' · cible ' + esc(x.cible) : ''}</span></td><td></td><td class="m">${x.dateFaite ? R.fmtDate(x.dateFaite) : ''}</td><td style="font-size:8.5pt">${esc(x.resultat || '')}${x.note ? '<br><i>' + esc(x.note) + '</i>' : ''}</td><td style="font-size:8pt">${x.par ? esc(R.userName(x.par)) : ''}</td></tr>`;
      const planUnifie = [...curesVis.map(c => ({ d: c.datePrevue + (c.heure || ''), h: ligneCure(c) })), ...ech.map(x => ({ d: x.echeance + '50', h: ligneCtrl(x) }))].sort((a, b) => a.d.localeCompare(b.d)).map(x => x.h).join('');
      const vides = n => Array.from({ length: n }, () => `<tr><td class="m">&nbsp;</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>`).join('');
      return `<div class="carnet-wrap">
      <div class="carnet-page">${band}
        <div class="doc-title">Carnet de suivi biothérapique</div><div class="doc-sub">${esc(R.PATHOS[p.pathologie]?.label)} — traitement par ${esc(pr.dci)}</div>
        <div class="doc-h2">Identité du patient</div>
        <dl class="doc-kv"><div><dt>Nom, prénom</dt><dd>${esc(p.nom)} ${esc(p.prenom)}</dd></div><div><dt>Né(e) le</dt><dd>${R.fmtDate(p.ddn)} (${R.age(p.ddn)} ans) · ${p.sexe === 'F' ? 'F' : 'M'}</dd></div><div><dt>IPP</dt><dd>${esc(p.ipp)}</dd></div><div><dt>Téléphone</dt><dd>${esc(p.tel || '')}</dd></div><div><dt>Poids / taille</dt><dd>${p.poids} kg · ${p.taille || '—'} cm</dd></div><div><dt>Allergies</dt><dd>${esc(p.allergies)}</dd></div><div><dt>Maladie</dt><dd>${esc(R.PATHOS[p.pathologie]?.label)} · Montréal ${esc(p.montreal)}</dd></div><div><dt>Diagnostic</dt><dd>${R.fmtDate(p.dateDiag, { month: 'long', year: 'numeric' })}</dd></div></dl>
        <div class="doc-h2">Traitement</div>
        <dl class="doc-kv"><div><dt>Biothérapie</dt><dd>${esc(pr.dci)} <span class="ui" style="font-weight:400">(${esc(pr.specialites)})</span></dd></div><div><dt>Classe</dt><dd>${esc(pr.classe)}</dd></div><div><dt>Voie</dt><dd>${esc(pr.voie)}</dd></div><div><dt>Présentation</dt><dd>${art ? esc(art.libelle) : '—'}</dd></div><div><dt>Schéma</dt><dd>${pr.induction.map(e => e.label).join(' · ')} puis ${esc(pr.entretien?.label || '')}${p.cycleCourant > 1 ? ` <span class="ui" style="font-weight:400">(cycle ${p.cycleCourant}, depuis le ${R.fmtDate(R.j0(p))})</span>` : ''}</dd></div><div><dt>Posologie actuelle</dt><dd>${esc(cureCourante?.doseTexte || '')}</dd></div><div><dt>Début du traitement</dt><dd>${R.fmtDate(p.dateDebut)}${p.cycleCourant > 1 ? ' · cycle en cours depuis le ' + R.fmtDate(R.j0(p)) : ''}</dd></div><div><dt>Prémédication</dt><dd>${esc(p.premedication || (p.cures.find(c => c.premedication && c.premedication !== 'Aucune') ? p.cures.filter(c => c.premedication && c.premedication !== 'Aucune').slice(-1)[0].premedication : 'Aucune'))}</dd></div><div><dt>Traitements associés</dt><dd>${esc(p.traitementsAssocies)}</dd></div><div><dt>Biothérapies antérieures</dt><dd>${esc(p.antecedentsBio)}</dd></div><div><dt>Médecin référent</dt><dd>${esc(R.userName(p.medecinId))}</dd></div><div><dt>Chef de service</dt><dd>${esc(s.chef)}</dd></div></dl>
        <div class="doc-box alert ui" style="margin-top:14px"><b>En cas de fièvre, d’infection ou de signe inhabituel, contactez l’hôpital de jour : ${esc(s.telHDJ)}</b><br>Urgences : ${esc(s.telUrgences)}. Présentez ce carnet à tout médecin, pharmacien, dentiste ou chirurgien.</div>
        <div class="doc-h2">Bilan pré-thérapeutique</div>
        <table class="doc-table"><thead><tr><th>Examen</th><th>Résultat</th><th>Date</th><th>Examen</th><th>Résultat</th><th>Date</th></tr></thead><tbody>${(() => { const rows = bilanApp.map(b => { const c = R.BILAN_PRE.find(x => x.id === b.id); return [esc(c.label.split(' (')[0].split(' :')[0]), b.statut === 'attente' ? 'en attente' : (b.statut === 'fait_anormal' ? 'anormal' : 'normal') + (b.commentaire ? ' — ' + esc(b.commentaire) : ''), b.date ? R.fmtDate(b.date) : '']; }); let h = ''; for (let i = 0; i < rows.length; i += 2) { const a = rows[i], b = rows[i + 1] || ['', '', '']; h += `<tr><td>${a[0]}</td><td>${a[1]}</td><td class="m">${a[2]}</td><td>${b[0]}</td><td>${b[1]}</td><td class="m">${b[2]}</td></tr>`; } return h; })()}</tbody></table>
        <p class="ui" style="font-size:9pt;margin:8px 0 0"><b>Vaccinations :</b> ${esc(vacc && vacc.commentaire ? vacc.commentaire : 'à compléter')} — vaccins vivants atténués contre-indiqués pendant le traitement et 3 mois après l’arrêt ; grippe chaque année, pneumocoque, hépatite B, HPV, zona recombinant recommandés.</p>
        ${foot(1)}</div>

      ${p.carnetMixte ? `<div class="carnet-page">${band}
        <div class="doc-h2" style="margin-top:0">Planification du traitement — séances et contrôles</div>
        <p class="ui" style="font-size:9pt;margin:0 0 8px;color:#4E5E59">Une seule chronologie : chaque ligne est une séance de perfusion ou un contrôle à réaliser. L’équipe note la date de réalisation, le résultat ou la tolérance, et signe. Objectifs STRIDE-II : disparition des symptômes, CRP normale, calprotectine < 250 µg/g, cicatrisation endoscopique à 6–12 mois.</p>
        ${histHTML}
        <table class="doc-table" style="margin-top:8px"><thead><tr><th>Date prévue</th><th>Élément</th><th>Dose</th><th>Réalisé le</th><th>Résultat / tolérance / notes</th><th>Visa</th></tr></thead><tbody>${planUnifie}${Array.from({ length: Math.max(3, 14 - curesVis.length - ech.length) }, () => '<tr><td class="m">&nbsp;</td><td></td><td></td><td></td><td></td><td></td></tr>').join('')}</tbody></table>
        <div class="doc-h2">À chaque séance</div>
        <ul class="doc-list ui" style="font-size:9.5pt">${p.surveillance.filter(x => x.mode === 'cure').map(x => `<li>${esc(x.label)}</li>`).join('')}<li>Poids, température, tension artérielle et pouls avant l’administration ; recherche d’une infection en cours ; grossesse éventuelle.</li>${pr.voie.includes('IV') ? `<li>Perfusion : ${esc(pr.dureePerfusion)}. ${esc(pr.surveillancePerf)}</li>` : ''}</ul>
        ${foot(2)}</div>
      <div class="carnet-page">${band}
        <div class="doc-h2" style="margin-top:0">Auto-surveillance entre les séances (à noter par le patient)</div>
        <table class="doc-table"><thead><tr><th>Date</th><th>Symptômes (selles/jour, sang, douleurs, fièvre)</th><th>Poids</th><th>Événement (infection, voyage, autre traitement…)</th></tr></thead><tbody>${Array.from({ length: 14 }, () => '<tr><td class="m">&nbsp;</td><td></td><td></td><td></td></tr>').join('')}</tbody></table>
        <div class="doc-h2">Injections à domicile (formes sous-cutanées)</div>
        <table class="doc-table"><thead><tr><th>Date</th><th>Dose</th><th>Site d’injection</th><th>Lot</th><th>Remarques</th></tr></thead><tbody>${Array.from({ length: 8 }, () => '<tr><td class="m">&nbsp;</td><td></td><td></td><td></td><td></td></tr>').join('')}</tbody></table>
        ${foot(3)}</div>` : `<div class="carnet-page">${band}
        <div class="doc-h2" style="margin-top:0">Tableau des séances — ${esc(pr.dci)}</div>${histHTML}
        <p class="ui" style="font-size:9pt;margin:0 0 8px;color:#4E5E59">Dose calculée sur le poids du jour. Le numéro de lot et la signature de l’infirmier(ère) sont reportés à chaque administration. Pour les injections sous-cutanées à domicile, le patient note la date, le site d’injection et le lot.</p>
        <table class="doc-table"><thead><tr><th>N°</th><th>Phase</th><th>Prévue le</th><th>Réalisée le</th><th>Poids</th><th>Dose</th><th>Lot</th><th>Tolérance / remarques</th><th>Visa IDE · PUI</th></tr></thead><tbody>
        ${curesVis.map(c => `<tr class="${c.statut === 'realisee' ? 'doc-done' : ''}"><td class="m">${c.n}</td><td>${esc(c.phase)} ${esc(c.label)}${(c.cycle || 1) > 1 ? ' (c' + c.cycle + ')' : ''}<br><span style="font-size:8pt;color:#7E8C88">${c.voie}</span></td><td class="m">${R.fmtDate(c.datePrevue)}</td><td class="m">${c.dateReelle ? R.fmtDate(c.dateReelle) : ''}</td><td class="m">${c.poids ? c.poids + ' kg' : ''}</td><td>${c.statut === 'realisee' ? (c.dose ? c.dose + ' mg' : esc(c.doseTexte)) : esc(c.doseTexte)}${c.flacons ? ` <span style="color:#7E8C88">(${c.flacons} u.)</span>` : ''}</td><td class="m">${esc(c.lot || '')}</td><td style="font-size:8.5pt">${c.statut === 'realisee' ? esc((c.tolerance || '').slice(0, 70)) : c.statut === 'reportee' ? 'Reportée — ' + esc((c.motif || '').slice(0, 50)) : ''}</td><td style="font-size:8pt">${c.statut === 'realisee' ? esc(R.userName(c.ide)) + (c.validationPharma ? ' · PUI ✓' : '') : ''}</td></tr>`).join('')}
        ${vides(Math.max(3, 18 - curesVis.length))}</tbody></table>
        ${foot(2)}</div>

      <div class="carnet-page">${band}
        <div class="doc-h2" style="margin-top:0">Calendrier des contrôles</div>
        <p class="ui" style="font-size:9pt;margin:0 0 8px;color:#4E5E59">Objectifs du traitement (STRIDE-II) : disparition des symptômes, CRP normale, calprotectine fécale < 250 µg/g, cicatrisation endoscopique à 6–12 mois.</p>
        <table class="doc-table"><thead><tr><th>Examen</th><th>Échéance</th><th>Réalisé le</th><th>Résultat</th><th>Visa</th></tr></thead><tbody>
        ${ech.map(x => `<tr class="${x.statut === 'faite' ? 'doc-done' : ''}"><td>${esc(x.label)}${x.cible ? `<br><span style="font-size:8pt;color:#7E8C88">Cible : ${esc(x.cible)}</span>` : ''}</td><td class="m">${R.fmtDate(x.echeance)} (${R.libelleJour(x.jour || 0)})</td><td class="m">${x.dateFaite ? R.fmtDate(x.dateFaite) : ''}</td><td style="font-size:9pt">${esc(x.resultat || '')}${x.note ? '<br><i>' + esc(x.note) + '</i>' : ''}</td><td style="font-size:8pt">${x.par ? esc(R.userName(x.par)) : ''}</td></tr>`).join('')}
        ${Array.from({ length: Math.max(2, 14 - ech.length) }, () => '<tr><td>&nbsp;</td><td></td><td></td><td></td><td></td></tr>').join('')}</tbody></table>
        <div class="doc-h2">À chaque cure</div>
        <ul class="doc-list ui" style="font-size:9.5pt">${p.surveillance.filter(x => x.mode === 'cure').map(x => `<li>${esc(x.label)}</li>`).join('')}<li>Poids, température, tension artérielle et pouls avant l’administration ; recherche d’une infection en cours (fièvre, toux, brûlures urinaires, plaie) ; grossesse éventuelle.</li>${pr.voie.includes('IV') ? `<li>Perfusion : ${esc(pr.dureePerfusion)}. ${esc(pr.surveillancePerf)}</li>` : ''}</ul>
        <div class="doc-h2">Auto-surveillance entre les cures (à noter par le patient)</div>
        <table class="doc-table"><thead><tr><th>Date</th><th>Symptômes (selles/jour, sang, douleurs, fièvre)</th><th>Poids</th><th>Événement (infection, voyage, autre traitement…)</th></tr></thead><tbody>${Array.from({ length: 6 }, () => '<tr><td class="m">&nbsp;</td><td></td><td></td><td></td></tr>').join('')}</tbody></table>
        ${foot(3)}</div>`}

      <div class="carnet-page">${band}
        <div class="doc-h2" style="margin-top:0">Conduite à tenir — informations pour le patient</div>
        <div class="doc-cols ui" style="font-size:9.5pt">
          <div><div class="doc-box alert"><b>Contactez rapidement l’hôpital de jour si :</b><ul class="doc-list"><li>fièvre ≥ 38 °C, frissons, fatigue inhabituelle ;</li><li>toux persistante, essoufflement, sueurs nocturnes ;</li><li>infection urinaire, cutanée, dentaire, ORL ou herpès / zona ;</li><li>diarrhée avec sang inhabituelle ou douleurs abdominales importantes ;</li><li>éruption cutanée, démangeaisons, gonflement du visage, gêne respiratoire pendant ou après l’administration ;</li><li>jaunisse, urines foncées ;</li><li>fourmillements, troubles de la vue, faiblesse d’un membre ;</li><li>ganglions, amaigrissement, lésion cutanée qui change.</li></ul></div>
            <div class="doc-box"><b>Infections</b><br>Le traitement diminue les défenses immunitaires. Toute infection doit être traitée avant la cure suivante : ne pas réaliser la cure sans avis médical. Lavage des mains, éviter les contacts avec des personnes malades, hygiène alimentaire (listériose : produits au lait cru, charcuterie artisanale).</div>
            <div class="doc-box"><b>Vaccinations</b><br>Vaccins vivants atténués (BCG, ROR, fièvre jaune, varicelle, zona vivant) <b>contre-indiqués</b> pendant le traitement et 3 mois après l’arrêt. Recommandés : grippe chaque année, pneumocoque, hépatite B, HPV, zona recombinant, dTP-coq. L’entourage peut être vacciné normalement.</div></div>
          <div><div class="doc-box"><b>Grossesse, allaitement, contraception</b><br>Informez l’équipe avant tout projet de grossesse : la plupart des biothérapies peuvent être poursuivies sur avis spécialisé ; certaines molécules (inhibiteurs de JAK, modulateurs S1P) imposent une contraception efficace. Le nourrisson exposé in utero ne doit pas recevoir de vaccin vivant avant 6 à 12 mois.</div>
            <div class="doc-box"><b>Chirurgie, soins dentaires, examens</b><br>Prévenez le chirurgien, le dentiste et l’hôpital de jour : le calendrier des cures peut être adapté autour de l’intervention. Signalez toute anesthésie ou hospitalisation.</div>
            <div class="doc-box"><b>Voyages</b><br>Avis médical avant un séjour en zone tropicale (fièvre jaune = vaccin vivant, paludisme, tuberculose). Les stylos et seringues sous-cutanés voyagent au frais (2–8 °C) avec l’ordonnance et ce carnet.</div>
            <div class="doc-box"><b>Autres médicaments</b><br>Ne prenez pas de nouveau médicament (y compris sans ordonnance, plantes, compléments) sans en parler au pharmacien. Anti-inflammatoires (AINS) déconseillés en cas de poussée.</div>
            <div class="doc-box"><b>Carte de surveillance</b><br>Gardez la carte patient de la biothérapie sur vous pendant le traitement et 4 mois après la dernière administration.</div></div>
        </div>
        <div class="doc-h2">Observations de l’équipe</div>
        <div class="doc-box" style="min-height:70px"></div>
        <div class="doc-sign"><div>Médecin référent<br><span style="color:#7E8C88">${esc(R.userName(p.medecinId))}</span></div><div>Pharmacien — analyse et éducation</div><div>Infirmier(ère) — hôpital de jour</div></div>
        ${foot(4)}</div>
      </div>`;
  };
})(window.RYZE);
